pipeline {
    agent { docker 'python:3.11' }  // Agente Docker

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-token', 
                    url: 'https://github.com/FranciscoPGuimaraes/Fintrack-API.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                pytest --html=report.html --self-contained-html --cov=./ --cov-report=html \
                    --log-cli-level=INFO --log-file=logfile.log --log-file-level=DEBUG
                '''
            }
        }

        stage('Upload Test Report') {
            steps {
                archiveArtifacts artifacts: 'report.html', allowEmptyArchive: true
            }
        }
    }
}
