pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-token', 
                    url: 'https://github.com/FranciscoPGuimaraes/Fintrack-API.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                script {
                    // Criando e ativando o ambiente virtual
                    sh '''#!/bin/bash
                    python3 -m venv venv
                    source venv/bin/activate
                    echo "Python executável: $(which python)"
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                pytest --html=report.html --self-contained-html --cov=./ --cov-report=html \
                    --log-cli-level=INFO --log-file=logfile.log --log-file-level=DEBUG
                '''
            }
        }

        stage('Upload Test Report') {
            steps {
                archiveArtifacts artifacts: 'report.html', allowEmptyArchive: true
            }
        }
    }
}
