pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-token', 
                    url: 'https://github.com/FranciscoPGuimaraes/Fintrack-API.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                script {
                    // Criando e ativando o ambiente virtual
                    sh '''#!/bin/bash
                    python3 -m venv venv
                    . venv/bin/activate
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

         stage('Build with PyInstaller') {
            steps {
                script {

                    sh '''#!/bin/bash
                    . venv/bin/activate  # Ativar o ambiente virtual
                    pyinstaller --onefile --clean src/main.py
                    '''
                }
            }
        }

        stage('Archive Executable') {
            steps {
                archiveArtifacts artifacts: 'dist/main', allowEmptyArchive: true
            }
        }

        stage('Run Tests') {
            steps {
                sh '''#!/bin/bash
                    . venv/bin/activate
                    pytest -v
                '''
            }
        }

        stage('Upload Test Report') {
            steps {
                archiveArtifacts artifacts: 'report.html', allowEmptyArchive: true
            }
        }
    }

    post {
        success {
            script {
                emailext(
                    to: "francisco.pereira@ges.inatel.br",
                    subject: "O pipeline foi executado",
                    body: "O pipeline foi executado com sucesso!"
                )
            }
        }

        failure {
            script {
                emailext(
                    to: "francisco.pereira@ges.inatel.br",
                    subject: "O pipeline foi executado",
                    body: "O pipeline falhou. Verifique os logs!"
                )
            }
        }
    }
}
